# Generated by Django 5.0.6 on 2024-05-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='activities/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('period', models.PositiveIntegerField(help_text='Period in minutes')),
                ('days_off', models.CharField(blank=True, help_text='Days off (comma-separated)', max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('start_time', models.TimeField(help_text='Start time of the activity')),
                ('end_time', models.TimeField(help_text='End time of the activity')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier')),
                ('categories', models.ManyToManyField(blank=True, related_name='activities', to='offers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='packages/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('period', models.PositiveIntegerField(help_text='Period in days')),
                ('days_off', models.CharField(blank=True, help_text='Days off (comma-separated)', max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(blank=True, related_name='packages', to='offers.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='tours/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('available_from', models.DateField()),
                ('available_to', models.DateField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('period', models.PositiveIntegerField(help_text='Period in days')),
                ('days_off', models.CharField(blank=True, help_text='Days off (comma-separated)', max_length=255, null=True)),
                ('unit', models.CharField(max_length=50)),
                ('categories', models.ManyToManyField(blank=True, related_name='tours', to='offers.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.supplier')),
            ],
            options={
                'verbose_name_plural': 'tours',
            },
        ),
    ]
