# Generated by Django 5.0.6 on 2024-05-30 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('offers', '0002_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitybooking',
            name='activity',
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitybooking',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='offers.period'),
            preserve_default=False,
        ),
    ]
